apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-scrapers-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:n-baranov/argo-apps.git
    targetRevision: HEAD
    path: scraper
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
